import type { Registry } from "@cosmjs/proto-signing";
import { isTsProtoGeneratedType } from "@cosmjs/proto-signing";

/**
 * @deprecated
 */
export function decodeMsg(myRegistry: Registry, type: string, msg: Uint8Array) {
  const msgType = myRegistry.lookupType(type);

  if (!msgType) {
    throw new Error("Type not found: " + type);
  }

  if (!isTsProtoGeneratedType(msgType)) {
    throw new Error("Type is not generated by ts-protobuf: " + type);
  }

  return msgType.decode(msg) as unknown;
}

/**
 * @deprecated
 */
export function msgToJSON(myRegistry: Registry, type: string, msg: Uint8Array) {
  const msgType = myRegistry.lookupType(type);

  if (!msgType) {
    throw new Error("Type not found: " + type);
  }

  if (!isTsProtoGeneratedType(msgType)) {
    throw new Error("Type is not generated by ts-protobuf: " + type);
  }

  // @ts-expect-error should be valid
  return msgType.toJSON(msgType.decode(msg));
}

/**
 * @deprecated
 */
export function uint8arrayToString(arr: Uint8Array) {
  return new TextDecoder().decode(arr);
}
