import { USDC_IBC_DENOMS } from "./network.config";

export const appConfig = {
  USDC_IBC_DENOMS,
  SIGN_AND_BROADCAST_RETRY_INITIAL_DELAY_MS: 500,
  TX_RECOVERY_RETRY_INITIAL_DELAY_MS: 1_000
};

export { AUTO_RELOAD_AMOUNT_MIN_USD, AUTO_RELOAD_THRESHOLD_MIN_USD, STANDARD_TOP_UP_MIN_AMOUNT_USD } from "./top-up.config";
