services:
  api:
    depends_on:
      db:
        condition: service_healthy

  indexer:
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      dockerfile: Dockerfile.db
    env_file:
      - .env.sandbox.docker-compose-dev
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/check-init.sh"]
      interval: 10s
      timeout: 5s
      retries: 20

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    ports:
      - "8080:8080"
    volumes:
      - ./oauth/login.html:/app/config/login.html:ro
    environment:
      JSON_CONFIG: |
        {
          "interactiveLogin": true,
          "loginPagePath": "/app/config/login.html",
          "tokenCallbacks": [
            {
              "issuerId": "default",
              "tokenExpiry": 3600,
              "requestMappings": [
                {
                  "requestParam": "code",
                  "match": "debug",
                  "claims": {
                    "sub": "user123",
                    "aud": ["my-audience"],
                    "email": "dev@example.com",
                    "nickname": "dev"
                  }
                },
                {
                  "requestParam": "client_id",
                  "match": "m2m-client",
                  "claims": {
                    "sub": "m2m-client",
                    "aud": ["my-audience"],
                    "scope": "read write"
                  }
                }
              ]
            }
          ]
        }

volumes:
  postgres_data:
    driver: local
