name: Slack notification about pending deployment approval
description: Sends a notification to Slack, notifying the user who merged the PR, about pending deployment approval

inputs:
  url:
    description: Base URL to Console API or UI
    required: true
  app:
    description: Application name
    required: true
  new-version:
    description: New app version
    required: true
  slack-webhook-url:
    description: Slack webhook URL
    required: false
  gh-user-to-slack-user:
    description: GitHub user to Slack user mapping
    required: false
    default: "{}"
  message-title:
    description: Title of the message
    required: false
    default: "Deployment requires approval"
  environment:
    description: Environment name
    required: false
    default: "staging" # or prod
  chain:
    description: Blockchain name (if applicable)
    required: false
    default: ""
  linked-workflow-run-id:
    description: The ID of the workflow run that called this action
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/associated-pr
      id: associated-pr
      with:
        gh-user-to-slack-user: ${{ inputs.gh-user-to-slack-user }}
    - name: Notify in Slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook-type: incoming-webhook
        webhook: ${{ inputs.slack-webhook-url }}
        payload: |
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: |
                  :hourglass_flowing_sand: *${{ inputs.message-title }}*

                  Hey ${{ steps.associated-pr.outputs.slack-user != '' && format('<@{0}>', steps.associated-pr.outputs.slack-user) || steps.associated-pr.outputs.author }},

                  A new version of *${{inputs.app}}* `${{ inputs.new-version }}` is ready to be deployed to *${{ inputs.environment }}${{ inputs.chain != '' && format('-{0}', inputs.chain) || '' }}*. Please test your changes on <${{ inputs.url }}|beta> and <${{ github.server_url }}/${{ github.repository }}/actions/workflows/reusable-deploy-k8s.yml|Confirm> the deployment.
                  This was triggered by the following PR:
                  <${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.associated-pr.outputs.number }}|${{ steps.associated-pr.outputs.title }}>

                  Alternatively, use gh cli to run workflow:
                  ```
                  gh workflow run reusable-deploy-k8s.yml \
                  -R akash-network/console \
                  -f app=${{ inputs.app }} \
                  -f appVersion=${{ inputs.new-version }} \
                  -f approve=true ${{ inputs.linked-workflow-run-id && format('-f linked-workflow-run-id={0}', inputs.linked-workflow-run-id) || '' }} \
                  -f environment=${{ inputs.environment }} ${{ inputs.chain && format('-f chain={0}', inputs.chain) || '' }}
                  && \
                  gh run list -R akash-network/console -w reusable-deploy-k8s.yml -L 1 \
                  --json status,displayTitle,headBranch,url \
                  --template '{{tablerow "STATUS" "TITLE" "BRANCH" "URL"}}{{range .}}{{tablerow .status .displayTitle .headBranch .url}}{{end}}'
                  ```
