#!/usr/bin/env -S node --experimental-strip-types
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const [, , specArg, outArg] = process.argv;
if (!specArg || !outArg) {
  console.error("Usage: gen-operations.ts <spec-path> <output-path>");
  process.exit(1);
}

const SPEC = resolve(process.cwd(), specArg);
const OUT = resolve(process.cwd(), outArg);

type ParameterObject = { name: string; in: "path" | "query" | "header" | "cookie" };
type OperationObject = {
  operationId?: string;
  tags?: string[];
  parameters?: ParameterObject[];
  requestBody?: unknown;
};
type PathItemObject = { parameters?: ParameterObject[] } & { [method: string]: OperationObject | ParameterObject[] | undefined };

type Spec = {
  paths?: Record<string, PathItemObject>;
};

type EmittedOperation = {
  path: string;
  method: string;
  operationId: string;
  pathParams: string[];
  queryParams: string[];
  hasBody: boolean;
};

const HTTP_METHODS = new Set(["get", "post", "put", "patch", "delete", "options", "head"]);

function main() {
  const raw = readFileSync(SPEC, "utf8");
  const doc = JSON.parse(raw) as Spec;

  const grouped: Record<string, Record<string, EmittedOperation>> = {};

  for (const [path, pathItem] of Object.entries(doc.paths ?? {})) {
    const sharedParams = pathItem.parameters ?? [];
    for (const [method, value] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method)) continue;
      const op = value as OperationObject;
      // Routes without operationId can't be addressed in the typed proxy; silently skip.
      // Most apps/api legacy routes lack operationId; only zod-openapi routes that explicitly set it appear in the operations table.
      if (!op.operationId) continue;
      // Group by the version segment anywhere in the path so consumers can address
      // operations as `client.v1.getThing(...)`. Matches both /v1/foo and
      // /internal/v1/foo so internal and public clients namespace identically.
      const versionMatch = path.match(/\/v(\d+)\//);
      const group = versionMatch ? `v${versionMatch[1]}` : op.tags?.[0] ?? "default";
      grouped[group] ??= {};
      const existing = grouped[group][op.operationId];
      if (existing) {
        throw new Error(
          `Duplicate operationId "${op.operationId}" in group "${group}": ${existing.method.toUpperCase()} ${existing.path} vs ${method.toUpperCase()} ${path}`
        );
      }
      const params = [...sharedParams, ...(op.parameters ?? [])];
      grouped[group][op.operationId] = {
        path,
        method,
        operationId: op.operationId,
        pathParams: params.filter(p => p.in === "path").map(p => p.name),
        queryParams: params.filter(p => p.in === "query").map(p => p.name),
        hasBody: Boolean(op.requestBody)
      };
    }
  }

  const lines: string[] = [];
  lines.push("// THIS FILE IS GENERATED by packages/console-api-types/scripts/gen-operations.ts. Do not edit.");
  lines.push("// Run `npm run generate -w @akashnetwork/console-api-types` to regenerate.");
  lines.push("");
  lines.push("export const operations = {");
  for (const [group, ops] of Object.entries(grouped)) {
    lines.push(`  ${JSON.stringify(group)}: {`);
    for (const [opId, op] of Object.entries(ops)) {
      const fields = [
        `path: ${JSON.stringify(op.path)}`,
        `method: ${JSON.stringify(op.method)}`,
        `operationId: ${JSON.stringify(op.operationId)}`,
        `pathParams: ${JSON.stringify(op.pathParams)}`,
        `queryParams: ${JSON.stringify(op.queryParams)}`,
        `hasBody: ${op.hasBody}`
      ].join(", ");
      lines.push(`    ${JSON.stringify(opId)}: { ${fields} },`);
    }
    lines.push(`  },`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type Operations = typeof operations;");
  lines.push("");

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join("\n"), "utf8");
  console.log(`wrote ${OUT}`);
}

main();
