// THIS FILE IS GENERATED by packages/console-api-types/scripts/gen-operations.ts. Do not edit.
// Run `npm run generate -w @akashnetwork/console-api-types` to regenerate.

export const operations = {
  v1: {
    purge: { path: "/internal/v1/users/{userId}/purge", method: "post", operationId: "purge", pathParams: ["userId"], queryParams: [], hasBody: false },
    createNotification: {
      path: "/internal/v1/jobs/notification",
      method: "post",
      operationId: "createNotification",
      pathParams: [],
      queryParams: [],
      hasBody: true
    }
  }
} as const;

export type Operations = typeof operations;
