// THIS FILE IS GENERATED by packages/console-api-types/scripts/gen-operations.ts. Do not edit.
// Run `npm run generate -w @akashnetwork/console-api-types` to regenerate.

export const operations = {
  v1: {
    createAlert: { path: "/v1/alerts", method: "post", operationId: "createAlert", pathParams: [], queryParams: [], hasBody: true },
    listAlerts: {
      path: "/v1/alerts",
      method: "get",
      operationId: "listAlerts",
      pathParams: [],
      queryParams: ["limit", "page", "type", "dseq"],
      hasBody: false
    },
    getAlert: { path: "/v1/alerts/{id}", method: "get", operationId: "getAlert", pathParams: ["id"], queryParams: [], hasBody: false },
    updateAlert: { path: "/v1/alerts/{id}", method: "patch", operationId: "updateAlert", pathParams: ["id"], queryParams: [], hasBody: true },
    deleteAlert: { path: "/v1/alerts/{id}", method: "delete", operationId: "deleteAlert", pathParams: ["id"], queryParams: [], hasBody: false },
    createNotificationChannel: {
      path: "/v1/notification-channels",
      method: "post",
      operationId: "createNotificationChannel",
      pathParams: [],
      queryParams: [],
      hasBody: true
    },
    listNotificationChannels: {
      path: "/v1/notification-channels",
      method: "get",
      operationId: "listNotificationChannels",
      pathParams: [],
      queryParams: ["limit", "page"],
      hasBody: false
    },
    createDefaultNotificationChannel: {
      path: "/v1/notification-channels/default",
      method: "post",
      operationId: "createDefaultNotificationChannel",
      pathParams: [],
      queryParams: [],
      hasBody: true
    },
    getNotificationChannel: {
      path: "/v1/notification-channels/{id}",
      method: "get",
      operationId: "getNotificationChannel",
      pathParams: ["id"],
      queryParams: [],
      hasBody: false
    },
    updateNotificationChannel: {
      path: "/v1/notification-channels/{id}",
      method: "patch",
      operationId: "updateNotificationChannel",
      pathParams: ["id"],
      queryParams: [],
      hasBody: true
    },
    deleteNotificationChannel: {
      path: "/v1/notification-channels/{id}",
      method: "delete",
      operationId: "deleteNotificationChannel",
      pathParams: ["id"],
      queryParams: [],
      hasBody: false
    },
    upsertDeploymentAlert: {
      path: "/v1/deployment-alerts/{dseq}",
      method: "post",
      operationId: "upsertDeploymentAlert",
      pathParams: ["dseq"],
      queryParams: [],
      hasBody: true
    },
    listDeploymentAlerts: {
      path: "/v1/deployment-alerts/{dseq}",
      method: "get",
      operationId: "listDeploymentAlerts",
      pathParams: ["dseq"],
      queryParams: [],
      hasBody: false
    }
  }
} as const;

export type Operations = typeof operations;
