apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: log-collector
  name: tenant-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list"]
