services:
  api:
    depends_on:
      db:
        condition: service_healthy

  indexer:
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: docker
      dockerfile: Dockerfile.db
    env_file:
      - .env.sandbox.docker-compose-dev
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/check-init.sh"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  postgres_data:
    driver: local
