/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { AlertsService } from "./AlertsService";
import { alertsService } from "./AlertsService";
import type { ContactPointsService } from "./ContactPointsService";
import { contactPointsService } from "./ContactPointsService";
export type Services = {
  alerts: AlertsService;
  contactPoints: ContactPointsService;
};
export const services = {
  alerts: alertsService,
  contactPoints: contactPointsService
} as const;
