/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { V1Service } from "./V1Service";
import { v1Service } from "./V1Service";
export type Services = {
  v1: V1Service;
};
export const services = {
  v1: v1Service
} as const;
