import { validateStaticEnvVars } from "./env-config.schema";

export const browserEnvConfig = validateStaticEnvVars({
  NEXT_PUBLIC_DEFAULT_NETWORK_ID: process.env.NEXT_PUBLIC_DEFAULT_NETWORK_ID,
  NEXT_PUBLIC_NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,

  // Network selection
  NEXT_PUBLIC_SELECTED_NETWORK: process.env.NEXT_PUBLIC_SELECTED_NETWORK,
  NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
  // Generic network configuration (populated from chain-specific .env files)
  NEXT_PUBLIC_NETWORK_TITLE: process.env.NEXT_PUBLIC_NETWORK_TITLE,
  NEXT_PUBLIC_CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
  NEXT_PUBLIC_CHAIN_REGISTRY_NAME: process.env.NEXT_PUBLIC_CHAIN_REGISTRY_NAME,
  NEXT_PUBLIC_NETWORK_TYPE: process.env.NEXT_PUBLIC_NETWORK_TYPE,
  NEXT_PUBLIC_RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_ENDPOINT,
  NEXT_PUBLIC_API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT,
  NEXT_PUBLIC_NETWORK_VERSION: process.env.NEXT_PUBLIC_NETWORK_VERSION,
  NEXT_PUBLIC_NETWORK_VERSION_MARKET: process.env.NEXT_PUBLIC_NETWORK_VERSION_MARKET,
  NEXT_PUBLIC_CONSOLE_API_URL: process.env.NEXT_PUBLIC_CONSOLE_API_URL,
  NEXT_PUBLIC_SECURITY_URL: process.env.NEXT_PUBLIC_SECURITY_URL,
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,

  NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID
});
