import { validateStaticEnvVars } from "./env-config.schema";

export const browserEnvConfig = validateStaticEnvVars({
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  NEXT_PUBLIC_DEFAULT_NETWORK_ID: process.env.NEXT_PUBLIC_DEFAULT_NETWORK_ID,
  NEXT_PUBLIC_NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
  NEXT_PUBLIC_CONSOLE_API_MAINNET_URL: process.env.NEXT_PUBLIC_CONSOLE_API_MAINNET_URL,
  NEXT_PUBLIC_BASE_SECURITY_URL: process.env.NEXT_PUBLIC_BASE_SECURITY_URL,
  NEXT_PUBLIC_MAINNET_RPC_URL: process.env.NEXT_PUBLIC_MAINNET_RPC_URL,
  NEXT_PUBLIC_MAINNET_API_URL: process.env.NEXT_PUBLIC_MAINNET_API_URL
});
