name: Detect dependencies on in-repo packages

inputs:
  path:
    description: 'Path to the workspace package'
    required: true

outputs:
  deps_json:
    description: 'List of application in-repo dependencies in JSON format'
    value: ${{ steps.deps.outputs.deps_json }}

runs:
  using: "composite"
  steps:
    - name: Find dependencies on in-repo packages
      id: deps
      shell: bash
      run: |
        node --input-type=module -e '
          import { findLocalPackageDependencies } from "./packages/releaser/find-local-package-dependencies.js";
          const localDependencies = findLocalPackageDependencies("./${{ inputs.path }}")
            .map(path => `${path}/**`);
          console.log(JSON.stringify(localDependencies));
        ' | xargs -I "{}" -0 echo "deps_json={}" >> $GITHUB_OUTPUT
