name: Detect dependencies on in-repo packages

inputs:
  app:
    description: 'Application to check'
    required: true

outputs:
  deps_json:
    description: 'List of application in-repo dependencies in JSON format'
    value: ${{ steps.deps.outputs.deps_json }}

runs:
  using: "composite"
  steps:
    - name: Find dependencies on in-repo packages
      id: deps
      shell: bash
      run: |
        node -e '
          const findLocalPackageDependencies = require("./packages/releaser/find-local-package-dependencies");
          const localDependencies = findLocalPackageDependencies("./apps/${{ inputs.app }}")
            .map(path => `${path}/**`);
          console.log(JSON.stringify(localDependencies));
        ' | xargs -I "{}" -0 echo "deps_json={}" >> $GITHUB_OUTPUT
