export type FeatureFlag =
  | "alerts"
  | "notifications_general_alerts_update"
  | "ui_deployment_closed_alert"
  | "billing_usage"
  | "ui_sdl_log_collector_enabled"
  | "maintenance_banner"
  | "auto_credit_reload"
  | "console_embedded_login"
  | "console_auth_passwordless"
  | "console_auth_password_escape_hatch"
  | "console_onboarding_redesign"
  | "bid_screening"
  | "ui_sdl_preview_panel"
  | "ui_build_and_deploy"
  | "ui_confidential_compute";
