export type FeatureFlag =
  | "notifications_general_alerts_update"
  | "ui_deployment_closed_alert"
  | "ui_sdl_log_collector_enabled"
  | "maintenance_banner"
  | "auto_credit_reload"
  | "ui_sdl_preview_panel"
  | "ui_build_and_deploy"
  | "ui_agent_mode_deploy"
  | "hackathons"
  | "deployment_runtime_limit"
  | "ui_sdl_proxy_http_options"
  | "ui_sdl_cpu_arch"
  | "fair_use_policy_gate"
  | "ui_deployments_list_redesign";
