"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProviderSnapshotsUrlParam = exports.ProviderSnapshots = exports.SnapshotsUrlParam = exports.Snapshots = void 0;
var Snapshots;
(function (Snapshots) {
    Snapshots["activeLeaseCount"] = "activeLeaseCount";
    Snapshots["totalUAktSpent"] = "totalUAktSpent";
    Snapshots["totalUUsdcSpent"] = "totalUUsdcSpent";
    Snapshots["totalUUsdSpent"] = "totalUUsdSpent";
    Snapshots["totalLeaseCount"] = "totalLeaseCount";
    Snapshots["activeCPU"] = "activeCPU";
    Snapshots["activeGPU"] = "activeGPU";
    Snapshots["activeMemory"] = "activeMemory";
    Snapshots["activeStorage"] = "activeStorage";
    Snapshots["dailyUAktSpent"] = "dailyUAktSpent";
    Snapshots["dailyUUsdcSpent"] = "dailyUUsdcSpent";
    Snapshots["dailyUUsdSpent"] = "dailyUUsdSpent";
    Snapshots["dailyLeaseCount"] = "dailyLeaseCount";
})(Snapshots || (exports.Snapshots = Snapshots = {}));
var SnapshotsUrlParam;
(function (SnapshotsUrlParam) {
    SnapshotsUrlParam["activeDeployment"] = "active-deployment";
    SnapshotsUrlParam["totalAKTSpent"] = "total-akt-spent";
    SnapshotsUrlParam["totalUSDCSpent"] = "total-usdc-spent";
    SnapshotsUrlParam["totalUSDSpent"] = "total-usd-spent";
    SnapshotsUrlParam["allTimeDeploymentCount"] = "all-time-deployment-count";
    SnapshotsUrlParam["compute"] = "compute";
    SnapshotsUrlParam["graphics"] = "graphics-gpu";
    SnapshotsUrlParam["memory"] = "memory";
    SnapshotsUrlParam["storage"] = "storage";
    SnapshotsUrlParam["dailyAktSpent"] = "daily-akt-spent";
    SnapshotsUrlParam["dailyUsdcSpent"] = "daily-usdc-spent";
    SnapshotsUrlParam["dailyUsdSpent"] = "daily-usd-spent";
    SnapshotsUrlParam["dailyDeploymentCount"] = "daily-deployment-count";
})(SnapshotsUrlParam || (exports.SnapshotsUrlParam = SnapshotsUrlParam = {}));
var ProviderSnapshots;
(function (ProviderSnapshots) {
    ProviderSnapshots["count"] = "count";
    ProviderSnapshots["cpu"] = "cpu";
    ProviderSnapshots["gpu"] = "gpu";
    ProviderSnapshots["memory"] = "memory";
    ProviderSnapshots["storage"] = "storage";
})(ProviderSnapshots || (exports.ProviderSnapshots = ProviderSnapshots = {}));
var ProviderSnapshotsUrlParam;
(function (ProviderSnapshotsUrlParam) {
    ProviderSnapshotsUrlParam["count"] = "active-providers";
    ProviderSnapshotsUrlParam["cpu"] = "compute-cpu";
    ProviderSnapshotsUrlParam["gpu"] = "graphics-gpu";
    ProviderSnapshotsUrlParam["memory"] = "memory";
    ProviderSnapshotsUrlParam["storage"] = "storage";
})(ProviderSnapshotsUrlParam || (exports.ProviderSnapshotsUrlParam = ProviderSnapshotsUrlParam = {}));
