---
version: "2.0"

services:
  syncer:
    image: redm4x/cloudmos-syncer:1.0.0
    env:
      - HealthchecksEnabled=true
      - SentryDSN=<SENTRY_DSN>
      - SentryServerName=<SENTRY_SERVER_NAME>
      - HealthChecks_SyncBlocks=<HEALTH_CHECKS_ID>
      - HealthChecks_SyncAKTPriceHistory=<HEALTH_CHECKS_ID>
      - HealthChecks_SyncProviderInfo=<HEALTH_CHECKS_ID>
      - HealthChecks_SyncKeybaseInfo=<HEALTH_CHECKS_ID>
      - ChainDatabaseCS=<DATABASE_CONNECTION_STRING>
      - ActiveChain=<CHAIN>
    expose:
      - port: 3079
        as: 80
        to:
          - global: true

  cloud-sql-proxy:
    image: redm4x/cloud-sql-proxy:1.31.2
    env:
      - KeyPath=/custom/proxy_key.json
      - ConnectionName=<CONNECTION_NAME>
      - Token=<TOKEN>
    command:
      - "sh"
      - "-c"
    args:
      - 'echo "${Token}" | base64 --decode > $KeyPath && /cloud_sql_proxy -instances=$ConnectionName=tcp:0.0.0.0:5432 -credential_file=$KeyPath'
    expose:
      - port: 5432
        as: 5432
        to:
          - service: syncer

profiles:
  compute:
    syncer:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 2Gi
    cloud-sql-proxy:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512mi
        storage:
          size: 2Gi
  placement:
    dcloud:
      pricing:
        syncer:
          denom: uakt
          amount: 1000
        cloud-sql-proxy:
          denom: uakt
          amount: 1000

deployment:
  syncer:
    dcloud:
      profile: syncer
      count: 1
  cloud-sql-proxy:
    dcloud:
      profile: cloud-sql-proxy
      count: 1
