name: Application security
description: Runs application security checks

inputs:
  path:
    required: true
  snyk-token:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Copy .dcignore
      shell: bash
      run: cp .dcignore ${{ inputs.path }}/.dcignore
    - name: Test code for security issues
      uses: snyk/actions/node@4a528b5c534bb771b6e3772656a8e0e9dc902f8b
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      with:
        command: code
        args: test ${{ inputs.path }} --severity-threshold=medium
