name: Console Web UI testing
description: Runs UI tests for Console Web

inputs:
  ref:
    description: Git ref related to the tests (e.g., console-web/v1.2.3)
    required: true
  url:
    description: Base URL to Console Web
    required: true
  test-wallet-mnemonic:
    description: Test wallet mnemonic
    required: true
  slack-webhook-url:
    description: Slack webhook URL
    required: false
  gh-user-to-slack-user:
    description: GitHub user to Slack user mapping
    required: false
    default: "{}"
  testing-client-token:
    description: E2E testing client token which allows to bypass captcha verification
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-app-deps
      with:
        app: deploy-web
    - name: Install Playwright Dependencies
      shell: bash
      working-directory: apps/deploy-web
      run: npx playwright install-deps chromium
    - name: Install Playwright Browsers
      shell: bash
      working-directory: apps/deploy-web
      run: npx playwright install --no-shell chromium
    - name: Run e2e tests
      id: e2e-tests
      env:
        TEST_WALLET_MNEMONIC: ${{ inputs.test-wallet-mnemonic }}
        BASE_URL: ${{ inputs.url }}
        E2E_TESTING_CLIENT_TOKEN: ${{ inputs.testing-client-token }}
        USER_DATA_DIR: ${{ runner.temp }}/chrome-profile-${{ github.run_id }}-${{ github.run_attempt }}
        CI: "true"
      shell: bash
      run: npm run test:e2e --workspace=apps/deploy-web
    - name: Tests cleanup
      if: ${{ !cancelled() }}
      shell: bash
      env:
        TEST_WALLET_MNEMONIC: ${{ inputs.test-wallet-mnemonic }}
      run: |
        npx --yes tsx@4.20.6 apps/deploy-web/script/closeDeployments.ts
    - uses: actions/upload-artifact@v4
      id: playwright-report
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: apps/deploy-web/playwright-report/
        retention-days: 5

    - uses: ./.github/actions/slack-tests-failed-notification
      if: ${{ !cancelled() && steps.e2e-tests.outcome == 'failure' }}
      with:
        ref: ${{ inputs.ref }}
        url: ${{ inputs.url }}
        gh-user-to-slack-user: ${{ inputs.gh-user-to-slack-user }}
        slack-webhook-url: ${{ inputs.slack-webhook-url }}
        message-title: "Console web UI tests failed on beta"

    - name: Summarize Test Results
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        echo "### ðŸ“ E2E Test Summary" >> $GITHUB_STEP_SUMMARY
        prefix=":white_check_mark: Passed"
        if [ "${{ steps.e2e-tests.outcome }}" == "failure" ]; then
          prefix=":x: Failed"
        fi
        echo "${prefix}, [download tests report](${{ steps.playwright-report.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY
