import dotenv from "dotenv";
dotenv.config();

export const env = {
  HEALTHCHECKS_SYNC_BLOCKS: process.env.HEALTHCHECKS_SYNC_BLOCKS,
  HEALTHCHECKS_SYNC_AKT_PRICE_HISTORY: process.env.HEALTHCHECKS_SYNC_AKT_PRICE_HISTORY,
  HEALTHCHECKS_SYNC_PROVIDER_INFO: process.env.HEALTHCHECKS_SYNC_PROVIDER_INFO,
  HEALTHCHECKS_SYNC_KEYBASE_INFO: process.env.HEALTHCHECKS_SYNC_KEYBASE_INFO,
  SENTRY_DSN: process.env.SENTRY_DSN,
  NODE_ENV: process.env.NODE_ENV,
  SENTRY_SERVER_NAME: process.env.SENTRY_SERVER_NAME,
  HEALTH_CHECKS_ENABLED: process.env.HEALTH_CHECKS_ENABLED,
  AKASH_DATABASE_CS: process.env.AKASH_DATABASE_CS,
  PASSAGE_DATABASE_CS: process.env.PASSAGE_DATABASE_CS,
  JUNO_DATABASE_CS: process.env.JUNO_DATABASE_CS,
  ACTIVE_CHAIN: process.env.ACTIVE_CHAIN,
  KEEP_CACHE: process.env.KEEP_CACHE === "true",
  STANDBY: process.env.STANDBY === "true",
  DATA_FOLDER: process.env.DATA_FOLDER ?? "./data"
};
