"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.assetLists = exports.akashTestnetAssetList = exports.akashSandboxAssetList = exports.akashAssetList = exports.akashTestnet = exports.akashSandbox = exports.akash = void 0;
var akash_1 = require("./akash");
Object.defineProperty(exports, "akash", { enumerable: true, get: function () { return akash_1.akash; } });
Object.defineProperty(exports, "akashAssetList", { enumerable: true, get: function () { return akash_1.akashAssetList; } });
var akash_sandbox_1 = require("./akash-sandbox");
Object.defineProperty(exports, "akashSandbox", { enumerable: true, get: function () { return akash_sandbox_1.akashSandbox; } });
Object.defineProperty(exports, "akashSandboxAssetList", { enumerable: true, get: function () { return akash_sandbox_1.akashSandboxAssetList; } });
var akash_testnet_1 = require("./akash-testnet");
Object.defineProperty(exports, "akashTestnet", { enumerable: true, get: function () { return akash_testnet_1.akashTestnet; } });
Object.defineProperty(exports, "akashTestnetAssetList", { enumerable: true, get: function () { return akash_testnet_1.akashTestnetAssetList; } });
exports.assetLists = [akash_1.akashAssetList, akash_sandbox_1.akashSandboxAssetList, akash_testnet_1.akashTestnetAssetList];
