name: Get Associated PR
description: Gets the associated PR for a commit (takes commit from github context)

inputs:
  gh-user-to-slack-user:
    description: GitHub user to Slack user mapping
    required: false
    default: "{}"

outputs:
  number:
    description: The number of the associated PR
    value: ${{ steps.associated-pr.outputs.number }}
  title:
    description: The title of the associated PR
    value: ${{ steps.associated-pr.outputs.title }}
  author:
    description: The author of the associated PR
    value: ${{ steps.associated-pr.outputs.author }}
  slack-user:
    description: The Slack user of the author
    value: ${{ steps.associated-pr.outputs.slack-user }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: associated-pr
      env:
        GH_USER_TO_SLACK_USER: ${{ inputs.gh-user-to-slack-user }}
      with:
        script: |
          let pr = context.payload.pull_request;

          // Retry logic to handle timing issues with GitHub API
          // Sometimes the commit-PR association isn't immediately available after merge
          if (!pr) {
            const maxRetries = 5;
            const baseDelay = 2000; // 2 seconds

            for (let attempt = 0; attempt < maxRetries; attempt++) {
              if (attempt > 0) {
                // Exponential backoff: 2s, 4s, 8s, 16s, 32s
                const delay = baseDelay * Math.pow(2, attempt - 1);
                core.info(`PR not found, retrying in ${delay}ms (attempt ${attempt + 1}/${maxRetries})...`);
                await new Promise(resolve => setTimeout(resolve, delay));
              }

              const response = (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              );

              if (response.data && response.data.length > 0) {
                pr = response.data[0];
                core.info(`Found PR #${pr.number} on attempt ${attempt + 1}`);
                break;
              }
            }
          }

          if (pr && !pr.merged_by) {
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            pr = data;
          }

          if (!pr) {
            core.warning(`No PR found for commit ${context.sha} after retries`);
            core.setOutput('number', '');
            core.setOutput('title', '');
            core.setOutput('author', '');
            core.setOutput('slack-user', '');
            return;
          }

          core.setOutput('number', pr.number);
          core.setOutput('title', pr.title);

          const author = pr.merged_by?.login || pr.user.login;
          core.setOutput('author', author);

          const userMapping = JSON.parse(process.env.GH_USER_TO_SLACK_USER || '{}');
          core.setOutput('slack-user', userMapping[author] || "");
