name: Get Associated PR
description: Gets the associated PR for a commit (takes commit from github context or sha input)

inputs:
  ref:
    description: Git ref or commit SHA to look up (defaults to github.sha)
    required: false
    default: ""
  gh-user-to-slack-user:
    description: GitHub user to Slack user mapping
    required: false
    default: "{}"

outputs:
  number:
    description: The number of the associated PR
    value: ${{ steps.associated-pr.outputs.number }}
  title:
    description: The title of the associated PR
    value: ${{ steps.associated-pr.outputs.title }}
  author:
    description: The author of the associated PR
    value: ${{ steps.associated-pr.outputs.author }}
  slack-user:
    description: The Slack user of the author
    value: ${{ steps.associated-pr.outputs.slack-user }}
  head_ref:
    description: The head branch ref of the PR
    value: ${{ steps.associated-pr.outputs.head_ref }}
  head_repo:
    description: The head repository full name of the PR
    value: ${{ steps.associated-pr.outputs.head_repo }}
  labels:
    description: Comma-separated list of PR labels
    value: ${{ steps.associated-pr.outputs.labels }}
  closed:
    description: Whether the PR is closed
    value: ${{ steps.associated-pr.outputs.closed }}

runs:
  using: "composite"
  steps:
    - name: Get commit SHA
      id: get-sha
      env:
        INPUT_REF: ${{ inputs.ref }}
      uses: actions/github-script@v7
      with:
        script: | # js
          if (!process.env.INPUT_REF) {
            core.info(`No ref input provided, using context.sha: ${context.sha}`);
            core.setOutput('sha', context.sha);
            return;
          }

          // handles console-web/v1.2.3 tags and inputs with typos console-web/vv1.2.3
          if (/^[\w-]+\/v{1,2}[\d.]+(-\w+\.\d+)?$/.test(process.env.INPUT_REF)) {
            core.info(`Ref input looks like app version tag, trying to resolve its sha: ${process.env.INPUT_REF}`);
            const { data } = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${process.env.INPUT_REF.replace(/\/v{2,}/, '/v')}`,
            });
            core.setOutput('sha', data.object.sha);
            return;
          }

          core.info(`Using provided ref as sha: ${process.env.INPUT_REF}`);
          core.setOutput('sha', process.env.INPUT_REF);

    - uses: actions/github-script@v7
      id: associated-pr
      env:
        GH_USER_TO_SLACK_USER: ${{ inputs.gh-user-to-slack-user }}
        INPUT_SHA: ${{ steps.get-sha.outputs.sha }}
      with:
        script: | # js
          const commitSha = process.env.INPUT_SHA || context.sha;
          let pr = context.payload.pull_request;

          if (!pr || pr.head?.sha !== commitSha) {
            const maxRetries = 5;
            const baseDelay = 2000;

            // Retry logic to handle timing issues with GitHub API
            // Sometimes the commit-PR association isn't immediately available after merge
            for (let attempt = 0; attempt < maxRetries; attempt++) {
              if (attempt > 0) {
                // Exponential backoff: 2s, 4s, 8s, 16s, 32s
                const delay = baseDelay * Math.pow(2, attempt - 1);
                core.info(`PR not found, retrying in ${delay}ms (attempt ${attempt + 1}/${maxRetries})...`);
                await new Promise(resolve => setTimeout(resolve, delay));
              }

              const response = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: commitSha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });

              if (response.data && response.data.length > 0) {
                pr = response.data[0];
                core.info(`Found PR #${pr.number} on attempt ${attempt + 1}`);
                break;
              }
            }
          }

          if (!pr) {
            core.warning(`No PR found for commit ${commitSha} after retries`);
            return;
          }

          if (pr.merged && !pr.merged_by) {
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            pr = data;
          }

          core.setOutput('number', pr.number);
          core.setOutput('title', pr.title);
          core.setOutput('head_ref', pr.head.ref);
          core.setOutput('head_repo', pr.head.repo?.full_name || '');
          core.setOutput('labels', (pr.labels || []).map(l => l.name).join(','));
          core.setOutput('closed', pr.closed_at ? 'true' : 'false');

          const author = pr.merged_by?.login || pr.user.login;
          core.setOutput('author', author);

          const userMapping = JSON.parse(process.env.GH_USER_TO_SLACK_USER || '{}');
          core.setOutput('slack-user', userMapping[author] || "");
