// THIS FILE IS GENERATED by packages/console-api-types/scripts/gen-operations.ts. Do not edit.
// Run `npm run generate -w @akashnetwork/console-api-types` to regenerate.

export const operations = {
  v1: {
    getStatus: { path: "/v1/status", method: "get", operationId: "getStatus", pathParams: [], queryParams: [], hasBody: false },
    listBlocks: { path: "/v1/blocks", method: "get", operationId: "listBlocks", pathParams: [], queryParams: ["limit"], hasBody: false },
    getBlock: { path: "/v1/blocks/{height}", method: "get", operationId: "getBlock", pathParams: ["height"], queryParams: [], hasBody: false },
    listAddressTransactions: {
      path: "/v1/addresses/{address}/transactions",
      method: "get",
      operationId: "listAddressTransactions",
      pathParams: ["address"],
      queryParams: ["skip", "limit"],
      hasBody: false
    },
    getNetworkStats: { path: "/v1/network-stats", method: "get", operationId: "getNetworkStats", pathParams: [], queryParams: ["days"], hasBody: false }
  }
} as const;

export type Operations = typeof operations;
