/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Returns ok */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              data: {
                /** @enum {string} */
                status: "ok";
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Indexer status with per-stream checkpoints */
    get: operations["getStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/blocks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the most recent blocks */
    get: operations["listBlocks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/blocks/{height}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a block with its transactions */
    get: operations["getBlock"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/addresses/{address}/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the transactions an address signed or moved coins in */
    get: operations["listAddressTransactions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/network-stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the current network activity and the most recent closed days */
    get: operations["getNetworkStats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns the indexer role, network, and checkpoints */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: {
              network: string;
              role: string;
              checkpoints: {
                stream: string;
                lastHeight: number;
                updatedAt: string;
              }[];
              deadLetters: {
                total: number;
                byType: {
                  type: string;
                  count: number;
                }[];
              };
              deferredIndexes: string[];
              jobs: {
                name: string;
                lastStartedAt: string;
                lastFinishedAt: string | null;
                /** @enum {string} */
                lastStatus: "running" | "success" | "failure";
                lastError: string | null;
                successCount: number;
                failureCount: number;
              }[];
            };
          };
        };
      };
    };
  };
  listBlocks: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The most recent blocks, newest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: {
              height: number;
              datetime: string;
              hash: string;
              proposer: {
                /** @description Consensus (hex) address of the proposer */
                address: string;
                operatorAddress: string | null;
                moniker: string | null;
              };
              transactionCount: number;
            }[];
          };
        };
      };
    };
  };
  getBlock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        height: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The block at that height with its transactions and their message types */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: {
              height: number;
              datetime: string;
              hash: string;
              proposer: {
                /** @description Consensus (hex) address of the proposer */
                address: string;
                operatorAddress: string | null;
                moniker: string | null;
              };
              transactionCount: number;
              parentHash: string | null;
              transactions: {
                index: number;
                hash: string;
                code: number;
                gasUsed: number;
                gasWanted: number;
                fee: {
                  denom: string;
                  amount: string;
                }[];
                messages: {
                  index: number;
                  type: string;
                }[];
              }[];
            };
          };
        };
      };
      /** @description The height is not indexed */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAddressTransactions: {
    parameters: {
      query?: {
        skip?: number | null;
        limit?: number;
      };
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of the address's transactions, newest first, with the total */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: {
              total: number;
              transactions: {
                height: number;
                datetime: string;
                hash: string;
                code: number;
                gasUsed: number;
                gasWanted: number;
                fee: {
                  denom: string;
                  amount: string;
                }[];
                /** @description How the address took part: it signed the transaction, or sent or received coins in it */
                roles: ("signer" | "sender" | "receiver")[];
                messages: {
                  index: number;
                  type: string;
                }[];
              }[];
            };
          };
        };
      };
    };
  };
  getNetworkStats: {
    parameters: {
      query?: {
        days?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active leases, resources and spend as of the last aggregated block, plus per-day rollups */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: {
              height: number;
              datetime: string;
              activeLeaseCount: number;
              totalLeaseCount: number;
              activeProviderCount: number;
              active: {
                cpuUnits: number;
                gpuUnits: number;
                memoryBytes: number;
                ephemeralStorageBytes: number;
                persistentStorageBytes: number;
              };
              totalSpent: {
                uakt: string;
                uusdc: string;
                uact: string;
              };
              daily: {
                date: string;
                closeHeight: number;
                activeLeaseCount: number;
                totalLeaseCount: number;
                dailyLeaseCount: number;
                activeProviderCount: number;
                active: {
                  cpuUnits: number;
                  gpuUnits: number;
                  memoryBytes: number;
                  ephemeralStorageBytes: number;
                  persistentStorageBytes: number;
                };
                totalSpent: {
                  uakt: string;
                  uusdc: string;
                  uact: string;
                };
                dailySpent: {
                  uakt: string;
                  uusdc: string;
                  uact: string;
                };
                dailyUsdSpent: string | null;
              }[];
            };
          };
        };
      };
      /** @description No block has been aggregated yet */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
