---
version: "2.0"

services:
  web:
    image: redm4x/console-deploy:<version>
    depends-on: proxy
    env:
      #      - API_BASE_URL=<API_URL_OVERRIDE>
      #      - NEXT_PUBLIC_GA_MEASUREMENT_ID=<GA_MEASUREMENT_ID>
      #      - NEXT_PUBLIC_SENTRY_DSN=<SENTRY_DSN>
      #      - NEXT_PUBLIC_SENTRY_SERVER_NAME=<SERVER_NAME>
      - MAINTENANCE_MODE=false
    expose:
      - port: 3001
        as: 80
        accept:
          - console.akash.network
        to:
          - global: true
  proxy:
    image: redm4x/console-provider-proxy:1.0.0-test1
    expose:
      - port: 3040
        as: 80
        accept:
          - console-provider-proxy.akash.network
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 500mi
        storage:
          size: 500mi
    proxy:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 500mi
        storage:
          size: 500mi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000
        proxy:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
  proxy:
    dcloud:
      profile: proxy
      count: 1
