/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { APIQueryClientServices, CreateAPIBasicClientOptions } from "@openapi-qraft/react";
import { qraftAPIClient } from "@openapi-qraft/react";
import { operationInvokeFn } from "@openapi-qraft/react/callbacks/operationInvokeFn";

import { services } from "./services/index";

const allCallbacks = { operationInvokeFn };
export function createAPIClient(options: CreateAPIBasicClientOptions): APIQueryClientServices<Services, typeof allCallbacks> {
  return qraftAPIClient(services, allCallbacks, options);
}
type Services = typeof services;
