/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import {
  type APIBasicClientServices,
  type APIBasicQueryClientServices,
  type APIUtilityClientServices,
  type CreateAPIBasicClientOptions,
  type CreateAPIBasicQueryClientOptions,
  type CreateAPIClientOptions,
  type CreateAPIQueryClientOptions,
  qraftAPIClient
} from "@openapi-qraft/react";
import * as callbacks from "@openapi-qraft/react/callbacks/index";

import { type Services, services } from "./services/index";
export function createAPIClient(options: CreateAPIQueryClientOptions): Services;
export function createAPIClient(options: CreateAPIBasicQueryClientOptions): APIBasicQueryClientServices<Services, ServiceMethods>;
export function createAPIClient(options: CreateAPIBasicClientOptions): APIBasicClientServices<Services, ServiceMethods>;
export function createAPIClient(): APIUtilityClientServices<Services, ServiceMethods>;
export function createAPIClient(
  options?: CreateAPIClientOptions
): Services | APIBasicClientServices<Services, ServiceMethods> | APIUtilityClientServices<Services, ServiceMethods> {
  if (!options) return qraftAPIClient<Services, ServiceMethods>(services, callbacks);
  if ("requestFn" in options) return qraftAPIClient<Services, ServiceMethods>(services, callbacks, options);
  return qraftAPIClient<Services, ServiceMethods>(services, callbacks, options);
}
type ServiceMethods = typeof callbacks;
