/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/alerts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createAlert"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/alerts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAlert"];
    put?: never;
    post?: never;
    delete: operations["deleteAlert"];
    options?: never;
    head?: never;
    patch: operations["patchAlert"];
    trace?: never;
  };
  "/v1/contact-points": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getContactPoints"];
    put?: never;
    post: operations["createContactPoint"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/contact-points/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getContactPoint"];
    put?: never;
    post?: never;
    delete: operations["deleteContactPoint"];
    options?: never;
    head?: never;
    patch: operations["patchContactPoint"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AlertCreateInput: {
      data:
        | {
            /** Format: uuid */
            contactPointId: string;
            /** @default true */
            enabled: boolean;
            summary: string;
            description: string;
            /** @enum {string} */
            type: "CHAIN_MESSAGE";
            conditions:
              | {
                  /** @enum {string} */
                  operator: "and";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    field: string;
                    value: string | number | boolean;
                  }[];
                }
              | {
                  /** @enum {string} */
                  operator: "or";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    field: string;
                    value: string | number | boolean;
                  }[];
                }
              | {
                  operator: "eq" | "lt" | "gt" | "lte" | "gte";
                  field: string;
                  value: string | number | boolean;
                };
          }
        | {
            /** Format: uuid */
            contactPointId: string;
            /** @default true */
            enabled: boolean;
            summary: string;
            description: string;
            /** @enum {string} */
            type: "DEPLOYMENT_BALANCE";
            conditions:
              | {
                  /** @enum {string} */
                  operator: "and";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    /** @enum {string} */
                    field: "balance";
                    value: number;
                  }[];
                }
              | {
                  /** @enum {string} */
                  operator: "or";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    /** @enum {string} */
                    field: "balance";
                    value: number;
                  }[];
                }
              | {
                  operator: "eq" | "lt" | "gt" | "lte" | "gte";
                  /** @enum {string} */
                  field: "balance";
                  value: number;
                };
            params: {
              dseq: string;
              owner: string;
            };
          };
    };
    AlertOutputResponse: {
      data:
        | {
            /** Format: uuid */
            contactPointId: string;
            enabled: boolean;
            summary: string;
            description: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            status: string;
            createdAt: unknown;
            updatedAt: unknown;
            /** @enum {string} */
            type: "CHAIN_MESSAGE";
            conditions:
              | {
                  /** @enum {string} */
                  operator: "and";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    field: string;
                    value: string | number | boolean;
                  }[];
                }
              | {
                  /** @enum {string} */
                  operator: "or";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    field: string;
                    value: string | number | boolean;
                  }[];
                }
              | {
                  operator: "eq" | "lt" | "gt" | "lte" | "gte";
                  field: string;
                  value: string | number | boolean;
                };
          }
        | {
            /** Format: uuid */
            contactPointId: string;
            enabled: boolean;
            summary: string;
            description: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            status: string;
            createdAt: unknown;
            updatedAt: unknown;
            /** @enum {string} */
            type: "DEPLOYMENT_BALANCE";
            conditions:
              | {
                  /** @enum {string} */
                  operator: "and";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    /** @enum {string} */
                    field: "balance";
                    value: number;
                  }[];
                }
              | {
                  /** @enum {string} */
                  operator: "or";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    /** @enum {string} */
                    field: "balance";
                    value: number;
                  }[];
                }
              | {
                  operator: "eq" | "lt" | "gt" | "lte" | "gte";
                  /** @enum {string} */
                  field: "balance";
                  value: number;
                };
            params: {
              dseq: string;
              owner: string;
            };
          };
    };
    ValidationErrorResponse: {
      statusCode: number;
      message: string;
      errors: {
        issues: Record<string, never>[];
      };
    };
    UnauthorizedErrorResponse: {
      statusCode: number;
      message: string;
    };
    ForbiddenErrorResponse: {
      statusCode: number;
      message: string;
    };
    InternalServerErrorResponse: {
      statusCode: number;
      message: string;
    };
    AlertPatchInput: {
      data: {
        /** Format: uuid */
        contactPointId?: string;
        /** @default true */
        enabled: boolean;
        summary?: string;
        description?: string;
        conditions?:
          | (
              | {
                  /** @enum {string} */
                  operator: "and";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    field: string;
                    value: string | number | boolean;
                  }[];
                }
              | {
                  /** @enum {string} */
                  operator: "or";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    field: string;
                    value: string | number | boolean;
                  }[];
                }
              | {
                  operator: "eq" | "lt" | "gt" | "lte" | "gte";
                  field: string;
                  value: string | number | boolean;
                }
            )
          | (
              | {
                  /** @enum {string} */
                  operator: "and";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    /** @enum {string} */
                    field: "balance";
                    value: number;
                  }[];
                }
              | {
                  /** @enum {string} */
                  operator: "or";
                  value: {
                    operator: "eq" | "lt" | "gt" | "lte" | "gte";
                    /** @enum {string} */
                    field: "balance";
                    value: number;
                  }[];
                }
              | {
                  operator: "eq" | "lt" | "gt" | "lte" | "gte";
                  /** @enum {string} */
                  field: "balance";
                  value: number;
                }
            );
      };
    };
    ContactPointCreateInput: {
      data: {
        name: string;
        /** @enum {string} */
        type: "email";
        config: {
          addresses: string[];
        };
      };
    };
    ContactPointOutput: {
      data: {
        name: string;
        /** @enum {string} */
        type: "email";
        config: {
          addresses: string[];
        };
        /** Format: uuid */
        id: string;
        /** Format: uuid */
        userId: string;
        createdAt: unknown;
        updatedAt: unknown;
      };
    };
    NotFoundErrorResponse: {
      statusCode: number;
      message: string;
    };
    ContactPointListOutput: {
      data: {
        name: string;
        /** @enum {string} */
        type: "email";
        config: {
          addresses: string[];
        };
        /** Format: uuid */
        id: string;
        /** Format: uuid */
        userId: string;
        createdAt: unknown;
        updatedAt: unknown;
      }[];
      pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
        hasNextPage: boolean;
        hasPreviousPage: boolean;
      };
    };
    ContactPointPatchInput: {
      data: {
        name?: string;
        /** @enum {string} */
        type?: "email";
        config?: {
          addresses: string[];
        };
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  createAlert: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AlertCreateInput"];
      };
    };
    responses: {
      /** @description Returns the created alert */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlertOutputResponse"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
  getAlert: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns the requested alert by id */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlertOutputResponse"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
  deleteAlert: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns the deleted alert */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlertOutputResponse"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
  patchAlert: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AlertPatchInput"];
      };
    };
    responses: {
      /** @description Returns the updated alert */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlertOutputResponse"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
  getContactPoints: {
    parameters: {
      query?: {
        /** @description Number of items per page */
        limit?: number;
        /** @description Page number */
        page?: number;
      };
      header?: {
        Authorization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns a paginated list of contact points */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactPointListOutput"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
  createContactPoint: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContactPointCreateInput"];
      };
    };
    responses: {
      /** @description Returns the created contact point */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactPointOutput"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
  getContactPoint: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns the requested contact point by id */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactPointOutput"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Returns 404 if the contact point is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotFoundErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
  deleteContactPoint: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns the deleted contact point */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactPointOutput"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Returns 404 if the contact point is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotFoundErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
  patchContactPoint: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContactPointPatchInput"];
      };
    };
    responses: {
      /** @description Returns the updated contact point */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContactPointOutput"];
        };
      };
      /** @description Validation error responded when some request parameters are invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ValidationErrorResponse"];
        };
      };
      /** @description Unauthorized error responded when the user is not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnauthorizedErrorResponse"];
        };
      };
      /** @description Forbidden error responded when the user is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForbiddenErrorResponse"];
        };
      };
      /** @description Returns 404 if the contact point is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotFoundErrorResponse"];
        };
      };
      /** @description Internal server error, should probably be reported */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternalServerErrorResponse"];
        };
      };
    };
  };
}
