#!/bin/bash

if [[ "$CI" != "true" ]]; then
    npm run update-apps-local-deps -w packages/database
    npm run update-apps-local-deps -w packages/env-loader
    npm run update-apps-local-deps -w packages/http-sdk
    npm run update-apps-local-deps -w packages/ui
    npm run update-apps-local-deps -w packages/network-store
    npm run update-apps-local-deps -w packages/logging
    git add ./apps/*/mvm.lock

    npx lint-staged
fi