#!/bin/bash

if [[ "$CI" != "true" ]]; then
    npm run generate -w packages/net
    git add ./packages/net/src/generated

    echo ""
    echo "Checking if package-lock.json and package.json are in sync..."
    echo ""
    npm ci --dry-run --ignore-scripts > /dev/null

    npx lint-staged
fi
