deploymentEnv: production
otel:
  enabled: true

chain: sandbox
hostNames:
  - console-api-sandbox.akash.network

replicas: 2

resources:
  limits:
    cpu: 2
    ephemeral-storage: 2Gi
    memory: 4Gi
  requests:
    cpu: 250m
    ephemeral-storage: 1Gi
    memory: 1Gi
