---
version: "2.0"

services:
  web:
    image: ghcr.io/akash-network/stats-web:<version>
#    env:
#      - API_BASE_URL=<API_URL_OVERRIDE>
#      - NEXT_PUBLIC_GA_MEASUREMENT_ID=<GA_MEASUREMENT_ID>
#      - NEXT_PUBLIC_SENTRY_DSN=<SENTRY_DSN>
#      - NEXT_PUBLIC_SENTRY_SERVER_NAME=<SERVER_NAME>
    expose:
      - port: 3000
        as: 80
        accept:
          - stats.akash.network
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 500mi
        storage:
          size: 500mi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
