---
version: "2.0"

services:
  api:
    image: {{IMAGE_NAME}}
    env:
      - DOPPLER_TOKEN={{DOPPLER_TOKEN}}
      - SENTRY_SERVER_NAME=akash
    expose:
      - port: 3000
        as: 80
        accept:
          - {{API_DOMAIN}}
        to:
          - global: true

profiles:
  compute:
    api:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 2Gi
  placement:
    dcloud:
      pricing:
        api:
          denom: uakt
          amount: 1000

deployment:
  api:
    dcloud:
      profile: api
      count: 1
