name: API CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  should-validate:
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      app: api
      workflow-trigger: ${{ github.event_name }}

  validate-api:
    needs: should-validate
    if: needs.should-validate.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-validate-app.yml
    secrets: inherit
    with:
      app: api
      test-command: |
        export POSTGRES_SKIP_IMPORT=true;
        npm run dc:up:db;
        npm run test:cov --workspace=apps/api;
        npm run dc:down;

  test-api-build:
    runs-on: ubuntu-latest
    needs: should-validate
    if: needs.should-validate.outputs.has_changes == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build the Docker image for API
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: packages/docker/script/dc.sh build api
