name: Deploy Deploy Web testnet

on:
  push:
    branches:
      - main-sdk-next
  workflow_dispatch:

jobs:
  should-deploy:
    name: Decide Whether to Deploy
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      path: apps/console-web

  build:
    needs: should-deploy
    name: Build Beta Docker image
    if: github.event_name == 'workflow_dispatch' || needs.should-deploy.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      tag: console-web/sdk53-beta
      tag-latest: false
      deployment-env: staging-testnet
      force-build: true

  deploy-beta:
    needs: build
    name: Deploy to beta sandbox
    if: needs.build.outputs.base_image_tag != ''
    uses: ./.github/workflows/reusable-deploy-k8s.yml
    secrets: inherit
    with:
      app: console-web-testnet
      appVersion: ${{ needs.build.outputs.base_image_tag }}
      environment: staging
      skip_beta_deployment_check: true
      force-rollout: true
