name: Validate and Build API

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-n-build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/local-dependencies
        id: local_deps
        with:
          app: api

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            local_deps: &local_deps ${{ steps.local_deps.outputs.deps_json }}
            api:
              - 'apps/api/**'
              - *local_deps

      - uses: ./.github/actions/setup-app-deps
        if: steps.filter.outputs.api == 'true'
        with:
          app: api

      - name: Run static code analysis
        if: steps.filter.outputs.api == 'true'
        run: npm run lint:api

      - name: Run tests
        if: steps.filter.outputs.api == 'true'
        env:
          POSTGRES_SKIP_IMPORT: true
        run: |
          npm run dc:up:db
          npm run test:cov --workspace=apps/api
          npm run dc:down

      - name: Build the Docker image for API
        if: steps.filter.outputs.api == 'true'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: packages/docker/script/dc.sh build api

      - name: Upload Test Coverage
        if: steps.filter.outputs.api == 'true'
        uses: codecov/codecov-action@v5
        with:
          directory: ./apps/api/coverage
          flags: api
          token: ${{ secrets.CODECOV_TOKEN }}
