name: Deploy Deploy Web testnet

on:
  push:
    branches:
      - main-sdk-next
  workflow_dispatch:

jobs:
  should-deploy:
    name: Decide Whether to Deploy
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      path: apps/console-web

  # needed for the in-place release to console-beta-testnet.akash.network
  build-beta-testnet:
    needs: should-deploy
    name: Build Beta Testnet Docker image
    if: github.event_name == 'workflow_dispatch' || needs.should-deploy.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      tag: console-web/sdk53-testnet-beta
      tag-latest: false
      deployment-env: staging-testnet
      force-build: true

  # needed for the eventual release to console-beta.akash.network during upgrade simulation
  build-beta:
    needs: should-deploy
    name: Build Beta Sandbox Docker image
    if: github.event_name == 'workflow_dispatch' || needs.should-deploy.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      tag: console-web/sdk53-sandbox-beta
      tag-latest: false
      deployment-env: staging
      force-build: true

  deploy-beta-testnet:
    needs: [build-beta-testnet, build-beta]
    name: Deploy to Beta Testnet
    if: needs.build-beta-testnet.outputs.base_image_tag != ''
    uses: ./.github/workflows/reusable-deploy-k8s.yml
    secrets: inherit
    with:
      app: console-web-testnet
      appVersion: ${{ needs.build-beta-testnet.outputs.base_image_tag }}
      environment: staging
      skip_beta_deployment_check: true
      force-rollout: true
