name: Indexer CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  should-validate:
    name: Decide Whether to Validate
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      app: indexer
      workflow-trigger: ${{ github.event_name }}

  validate-indexer:
    needs: should-validate
    if: needs.should-validate.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-validate-app.yml
    secrets: inherit
    with:
      app: indexer

  test-indexer-build:
    runs-on: ubuntu-latest
    needs: should-validate
    if: needs.should-validate.outputs.has_changes == 'true'

    steps:
      - uses: actions/checkout@v4
      - run: packages/docker/script/dc.sh build indexer
