name: "Local Package CI"

on:
  pull_request:
    branches: ["main"]
    paths:
      - "packages/**"
      - ".github/workflows/local-packages-validate.yml"

jobs:
  validate:
    name: Validate local packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-app-deps

      - name: Static analysis
        run: npm run lint -w ./packages --if-present -- --quiet

      - name: Type checking
        run: npm run validate:types -w ./packages --if-present

      - name: Run local package tests
        run: npm run test -w ./packages --if-present
