name: Local Package Validation

on:
  pull_request:
    branches: ["main"]
    paths:
      - "packages/**"
      - ".github/workflows/local-packages-validate.yml"

jobs:
  validate:
    name: Validate local packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Static analysis
        run: npm run lint -w ./packages --if-present -- --quiet

      - name: Type checking
        run: npm run validate:types -w ./packages --if-present

      - name: Run local package tests
        run: npm run test -w ./packages --if-present
