name: "Log Collector CI"

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  should-validate:
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      path: apps/log-collector

  validate:
    needs: should-validate
    if: needs.should-validate.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-validate-app.yml
    secrets: inherit
    with:
      app: log-collector

  log-collector-ci:
    runs-on: ubuntu-latest
    needs: [should-validate, validate]
    if: always()
    steps:
      - name: Check statuses
        if: needs.should-validate.outputs.has_changes == 'true'
        env:
          VALIDATE_RESULT: ${{ needs.validate.result }}
        run: |
          echo "Validate: $VALIDATE_RESULT"
          if [[ "$VALIDATE_RESULT" != "success" ]]; then
            exit 1
          fi
