name: Deploy Notifications testnet

on:
  push:
    branches:
      - main-sdk-next
  workflow_dispatch:

jobs:
  should-deploy:
    name: Decide Whether to Deploy
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      path: apps/notifications

  build:
    needs: should-deploy
    name: Build Docker image
    if: github.event_name == 'workflow_dispatch' || needs.should-deploy.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      tag: notifications/sdk53
      tag-latest: false
      deployment-env: staging-testnet
      force-build: true

  deploy-beta:
    needs: build
    name: Deploy to beta sandbox
    uses: ./.github/workflows/reusable-deploy-k8s.yml
    secrets: inherit
    with:
      app: notifications-testnet
      appVersion: ${{ needs.build.outputs.image_tag }}
      environment: staging
