name: Validate and Build Notifications

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-n-build-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect Local Deps Changes
        uses: ./.github/actions/local-dependencies
        id: local_deps
        with:
          app: notifications

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            local_deps: &local_deps ${{ steps.local_deps.outputs.deps_json }}
            notifications:
              - 'apps/notifications/**'
              - *local_deps

      - uses: ./.github/actions/setup-app-deps
        if: steps.filter.outputs.notifications == 'true'
        with:
          app: notifications

      - name: Run static code analysis
        if: steps.filter.outputs.notifications == 'true'
        run: npm run lint -w apps/notifications

      - name: Run tests
        if: steps.filter.outputs.notifications == 'true'
        env:
          POSTGRES_SKIP_IMPORT: true
        run: |
          npm run test:cov --workspace=apps/notifications

      - name: Upload Test Coverage
        if: steps.filter.outputs.notifications == 'true'
        uses: codecov/codecov-action@v5
        with:
          directory: ./apps/notifications/coverage
          flags: notifications
          token: ${{ secrets.CODECOV_TOKEN }}
