name: Notifications CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  should-validate:
    name: Decide Whether to Validate
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      app: notifications

  validate-notifications:
    runs-on: ubuntu-latest
    needs: should-validate
    if: needs.should-validate.outputs.enabled == 'true'

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-app-deps
        with:
          app: notifications

      - name: Run static code analysis
        if: github.event_name == 'pull_request'
        run: npm run lint -w apps/notifications -- --quiet

      - name: Run tests
        env:
          POSTGRES_SKIP_IMPORT: true
        run: |
          npm run dc:up:db
          npm run test:cov --workspace=apps/notifications
          npm run dc:down

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./apps/notifications/coverage
          flags: notifications
          token: ${{ secrets.CODECOV_TOKEN }}
