name: Notifications CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  should-validate:
    name: Decide Whether to Validate
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      app: notifications
      workflow-trigger: ${{ github.event_name }}

  validate-notifications:
    needs: should-validate
    if: needs.should-validate.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-validate-app.yml
    secrets: inherit
    with:
      app: notifications
      test-command: |
        export POSTGRES_SKIP_IMPORT=true;
        npm run dc:up:db;
        npm run test:cov --workspace=apps/notifications;
        npm run dc:down;

  test-notifications-build:
    runs-on: ubuntu-latest
    needs: should-validate
    if: needs.should-validate.outputs.has_changes == 'true'
    steps:
      - uses: actions/checkout@v4
      - run: packages/docker/script/dc.sh build notifications
