name: Provider Proxy CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  should-validate:
    name: Decide Whether to Validate
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      app: provider-proxy
      workflow-trigger: ${{ github.event_name }}

  validate-provider-proxy:
    needs: should-validate
    if: needs.should-validate.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-validate-app.yml
    secrets: inherit
    with:
      app: provider-proxy

  test-provider-proxy-build:
    runs-on: ubuntu-latest
    needs: should-validate
    if: needs.should-validate.outputs.has_changes == 'true'

    steps:
      - uses: actions/checkout@v4
      - run: packages/docker/script/dc.sh build provider-proxy
