name: Provider Console CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  should-validate:
    name: Decide Whether to Validate
    uses: ./.github/workflows/reusable-should-validate.yml
    with:
      app: provider-console
      workflow-trigger: ${{ github.event_name }}

  validate-provider-console:
    needs: should-validate
    if: needs.should-validate.outputs.enabled == 'true'
    uses: ./.github/workflows/reusable-validate-app.yml
    secrets: inherit
    with:
      app: provider-console

  test-provider-console-build:
    runs-on: ubuntu-latest
    needs: should-validate
    if: needs.should-validate.outputs.has_changes == 'true'

    steps:
      - uses: actions/checkout@v4
      - run: packages/docker/script/dc.sh build provider-console --build-arg DEPLOYMENT_ENV=production
