name: Deploy Provider Console CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-provider-console:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/local-dependencies
        id: local_deps
        with:
          app: provider-console

      # Check for changes in provider-console folder
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            local_deps: &local_deps ${{ steps.local_deps.outputs.deps_json }}
            provider-console:
              - 'apps/provider-console/**'
              - *local_deps

      - name: Build the Docker image
        if: steps.filter.outputs.provider-console == 'true'
        run: packages/docker/script/dc.sh build provider-console --build-arg DEPLOYMENT_ENV=production
