name: Release API

on:
  push:
    branches:
      - main
    paths:
      - "apps/api/package.json"

jobs:
  release:
    name: Create Release
    uses: ./.github/workflows/create-github-release.yml
    secrets: inherit
    with:
      app: api

  build:
    needs: release
    name: Build Docker image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      tag: ${{ needs.release.outputs.version }}

  release-beta-mainnet:
    needs: build
    name: Deploy to beta sandbox
    uses: ./.github/workflows/deploy-k8s.yml
    secrets: inherit
    with:
      app: console-api
      appVersion: ${{ needs.build.outputs.image_tag }}
      environment: staging
      chain: mainnet

  release-beta-sandbox:
    needs: build
    name: Deploy to beta sandbox
    uses: ./.github/workflows/deploy-k8s.yml
    secrets: inherit
    with:
      app: console-api
      appVersion: ${{ needs.build.outputs.image_tag }}
      environment: staging
      chain: sandbox
